name: lunar-e2e-pin-rotation-f8ed44d33
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened f8ed44d33'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-f8ed44d33'
    runs-on: localdev-e2e-test-37450673998-1-github-3-e2e
    steps:
      - run: /bin/echo 'pin rotation CI f8ed44d33'
